# Generated by Django 5.2.1 on 2025-06-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('ventas', '0002_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='metodo_pago',
            field=models.CharField(default='Tarjeta', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterModelTable(
            name='ordenventa',
            table='orden_venta',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
