# Generated by Django 5.2.1 on 2025-05-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
    ]
