# Generated by Django 5.2.1 on 2025-06-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.producto'),
        ),
    ]
