# Generated by Django 5.2.1 on 2025-06-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
